<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <title>Index</title>
    </head>
    <body>
        <h1> site name -  <?= $site ?></h1>
        <?php if(!empty($map)) : ?>
            <ul>
                <?php foreach ($map as $item) : ?>
                    <li>
                        <?= $item ?>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
     </body>
</html>